set(CMSIS_STM32F0_DEFINITIONS
	STM32F051x8
    $<$<CONFIG:Debug>:DEBUG>
)

set(CMSIS_STM32F0_INCLUDE_DIRS SYSTEM
	${CMAKE_CURRENT_SOURCE_DIR}/STM32F0xx/Include
	${CMAKE_CURRENT_SOURCE_DIR}/CMSIS/Core/Include
)

set(CMSIS_STM32F0_SOURCES
	# No template source files used, only headers.
)

add_library(CMSIS_STM32F0 INTERFACE)
target_include_directories(CMSIS_STM32F0 INTERFACE ${CMSIS_STM32F0_INCLUDE_DIRS})
target_compile_definitions(CMSIS_STM32F0 INTERFACE ${CMSIS_STM32F0_DEFINITIONS})

